### PR TITLE
I added the browsing options  for the excel files

### PR DESCRIPTION
**Pull request by saikrishnak7**

### CODE REVIEW

**Comment by vasi786** [comment]
Got it

**Comment by vasi786** [comment]
Arey nv raasina code antha starting lo undaali kadha ra

**Comment by saikrishnak7** [comment]
haa avnu

**Comment by saikrishnak7** [comment]
ninu last lo pettina. First lo pettu

**Comment by vasi786** [comment]
And message boxes for first two were not included

**Comment by saikrishnak7** [comment]
cheyyala aadhi kuda

**Comment by vasi786** [comment]
> ninu last lo pettina. First lo pettu

Okay adhi nen chesta

**Comment by vasi786** [comment]
> cheyyala aadhi kuda

cheesi anni kalipi okasare pampu

**Comment by vasi786** [comment]
Function file, and these changes

**Comment by saikrishnak7** [comment]
done....malli eppati lagane pamputha

**Comment by vasi786** [comment]
Haa same. em chesina chey nv kaani pakka fork chuskoo. fork meedha kottinankane next editing uploading cheskooo

**Pull request closed without merging**
