### PR TITLE
I have the excel file and the matlab code

### PR DESCRIPTION
**Pull request by vasi786**
A small piece of code is written just to get the column indices of column names such as names, CGPA

We need to get the column indices of the excel file first then we can extract that column and treat it seperately.

### CODE REVIEW

**Comment by vasi786** [comment]
You can comment like this at the bottom

**Comment by saikrishnak7** [comment]
write the comments in the code. so that everyone can understand easily

**Comment by vasi786** [comment]
You can do that @saikrishnak7

**Comment by saikrishnak7** [comment]
what does that book1 file include

**Comment by vasi786** [comment]
lemme make merge pull request, then you can download the files edit it and reupload and pull request

**Pull request merged**
